# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

WORKDIR /app

# Copy source code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir httpx>=0.28.1 "mcp[cli]>=1.6.0" "python-dotenv>=1.1.0"

EXPOSE 8000

CMD ["python", "main.py"]
